### ISSUE TITLE
No body found on empty Kotlin Class

### ISSUE THREAD

**Issue by nomisRev** [openrewrite/rewrite-kotlin#20]
Reproducing example can be found here: https://github.com/nomisRev/rewrite-arrow/pull/2

Attempted to rewrite the `JavaIsoVisitor` example of [Writing a Java Refactoring Recipe](https://docs.openrewrite.org/authoring-recipes/writing-a-java-refactoring-recipe) to Kotlin, and ran into the following error.

I tried to keep the changes in this PR to a minimal, but some additional information:
 - Same issue occurs when using `KotlinIsoVisitor`
 - Same issue occurs if using `JavaTemplate.builder(this::getCursor, "public fun hello(): String { return \"Hello from #{}!\" }")`
 - As the stacktrace below indicates the line triggering this exception in the user code is `J.withTemplate` on [line 74](https://github.com/nomisRev/rewrite-arrow/blob/0f4730113428263cf722cfb5afc8c89867f74ecc/src/main/java/arrow/SayHelloRecipe.java#L74) in `SayHelloRecipe.java`.

Failing with following output:

```text
java.lang.AssertionError: Failed to parse sources or run recipe
	at org.openrewrite.test.RewriteTest.lambda$defaultExecutionContext$11(RewriteTest.java:511)
	at org.openrewrite.RecipeScheduler.lambda$scheduleVisit$4(RecipeScheduler.java:274)
	at org.openrewrite.RecipeScheduler.lambda$mapAsync$0(RecipeScheduler.java:56)
	at org.openrewrite.scheduling.DirectScheduler.schedule(DirectScheduler.java:35)
	at org.openrewrite.RecipeScheduler.mapAsync(RecipeScheduler.java:57)
	at org.openrewrite.RecipeScheduler.scheduleVisit(RecipeScheduler.java:236)
	at org.openrewrite.test.RecipeSchedulerCheckingExpectedCycles.scheduleVisit(RecipeSchedulerCheckingExpectedCycles.java:50)
	at org.openrewrite.RecipeScheduler.scheduleRun(RecipeScheduler.java:101)
	at org.openrewrite.Recipe.run(Recipe.java:330)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:319)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:128)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:123)
	at arrow.SayHelloRecipeTest.addsHelloToFooBar(SayHelloRecipeTest.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: org.openrewrite.internal.RecipeRunException: Exception while visiting project file 'null (in FooBar)', caused by: java.lang.NullPointerException: Cannot invoke "org.openrewrite.java.tree.J$Block.getMarkers()" because the return value of "org.openrewrite.java.tree.J$ClassDeclaration.getBody()" is null, at org.openrewrite.kotlin.internal.KotlinPrinter$KotlinJavaPrinter.visitClassDeclaration(KotlinPrinter.java:303)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:324)
	at app//org.openrewrite.kotlin.internal.KotlinPrinter$KotlinJavaPrinter.visit(KotlinPrinter.java:198)
	at app//org.openrewrite.kotlin.internal.KotlinPrinter.visit(KotlinPrinter.java:45)
	at app//org.openrewrite.kotlin.internal.KotlinPrinter.visit(KotlinPrinter.java:38)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:172)
	at app//org.openrewrite.Tree.print(Tree.java:93)
	at app//org.openrewrite.Tree.print(Tree.java:89)
	at app//org.openrewrite.Tree.printTrimmed(Tree.java:108)
	at app//org.openrewrite.java.internal.template.BlockStatementTemplateGenerator.classDeclaration(BlockStatementTemplateGenerator.java:538)
	at app//org.openrewrite.java.internal.template.BlockStatementTemplateGenerator.template(BlockStatementTemplateGenerator.java:189)
	at app//org.openrewrite.java.internal.template.BlockStatementTemplateGenerator.lambda$template$0(BlockStatementTemplateGenerator.java:84)
	at app//io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:65)
	at app//org.openrewrite.java.internal.template.BlockStatementTemplateGenerator.template(BlockStatementTemplateGenerator.java:71)
	at app//org.openrewrite.java.internal.template.JavaTemplateParser.parseBlockStatements(JavaTemplateParser.java:158)
	at app//org.openrewrite.java.internal.template.JavaTemplateJavaExtension$1.visitBlock(JavaTemplateJavaExtension.java:80)
	at app//org.openrewrite.java.internal.template.JavaTemplateJavaExtension$1.visitBlock(JavaTemplateJavaExtension.java:59)
	at app//org.openrewrite.java.tree.J$Block.acceptJava(J.java:761)
	at app//org.openrewrite.java.tree.J.accept(J.java:64)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:172)
	at app//org.openrewrite.java.JavaTemplate.withTemplate(JavaTemplate.java:107)
	at app//org.openrewrite.java.JavaTemplate.withTemplate(JavaTemplate.java:39)
	at app//org.openrewrite.java.tree.J.withTemplate(J.java:91)
	at app//arrow.SayHelloRecipe$SayHelloVisitor.visitClassDeclaration(SayHelloRecipe.java:76)
	at app//arrow.SayHelloRecipe$SayHelloVisitor.visitClassDeclaration(SayHelloRecipe.java:45)
	at app//org.openrewrite.java.tree.J$ClassDeclaration.acceptJava(J.java:1211)
	at app//org.openrewrite.java.tree.J.accept(J.java:64)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
	at app//org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
	at app//org.openrewrite.kotlin.KotlinVisitor.lambda$visitCompilationUnit$2(KotlinVisitor.java:54)
	at app//org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:145)
	at app//org.openrewrite.internal.ListUtils.map(ListUtils.java:126)
	at app//org.openrewrite.internal.ListUtils.map(ListUtils.java:145)
	at app//org.openrewrite.kotlin.KotlinVisitor.visitCompilationUnit(KotlinVisitor.java:54)
	at app//org.openrewrite.kotlin.KotlinVisitor.visitJavaSourceFile(KotlinVisitor.java:42)
	at app//org.openrewrite.kotlin.tree.K$CompilationUnit.acceptKotlin(K.java:177)
	at app//org.openrewrite.kotlin.tree.K.accept(K.java:48)
	at app//org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
	at app//org.openrewrite.RecipeScheduler.lambda$scheduleVisit$4(RecipeScheduler.java:270)
	... 94 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.openrewrite.java.tree.J$Block.getMarkers()" because the return value of "org.openrewrite.java.tree.J$ClassDeclaration.getBody()" is null
	at org.openrewrite.kotlin.internal.KotlinPrinter$KotlinJavaPrinter.visitClassDeclaration(KotlinPrinter.java:303)
	at org.openrewrite.kotlin.internal.KotlinPrinter$KotlinJavaPrinter.visitClassDeclaration(KotlinPrinter.java:191)
	at org.openrewrite.java.tree.J$ClassDeclaration.acceptJava(J.java:1211)
	at org.openrewrite.java.tree.J.accept(J.java:64)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
	... 132 more
```

**Comment by traceyyoshima** [comment]
Update: I tested this on the sample project, and the parser returns a body. The NPE occurs using the `JavaTemplate`.

**Comment by traceyyoshima** [comment]
This isn't a bug -- The JavaTemplate cannot parse Kotlin code.
The parser handles Kotlin appropriately, but we do not have a Kotlin template yet.

**Comment by nomisRev** [comment]
@traceyyoshima should this be turned into a ticket for a KotlinTemplate? Or is this currently not in the scope or the rewrite-Kotlin project?

**Comment by ckcd** [comment]
@traceyyoshima does that means only some specific recipes (e.g. `new KotlinVisitor<ExecutionContext>()`) can handle kotlin files ?

**Comment by knutwannheden** [comment]
Meanwhile we have `KotlinTemplate` support as you can see in this recipe: https://github.com/openrewrite/rewrite-kotlin/blob/ac109fa98e4ebd942db21ec9f4806cbf993f7784/src/main/java/org/openrewrite/kotlin/cleanup/ReplaceCharToIntWithCode.java#L52-L55

Let us know how this works for you.
