### ISSUE TITLE
Parse error when incrementing array element

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite-kotlin#291]
The following test fails
```java
    @Test
    void incrementArrayElement() {
        rewriteRun(
          kotlin(
            """
              val array = IntArray(1)
              array.let {
                  it[0]++
              }
              val x = array[0]++
              """
          )
        );
    }
```

```
java.lang.IllegalStateException: Unresolved function.
	at org.openrewrite.kotlin.internal.KotlinParserVisitor.visitSimpleFunction(KotlinParserVisitor.kt:2620)
	at org.openrewrite.kotlin.internal.KotlinParserVisitor.visitElement0(KotlinParserVisitor.kt:4563)
	at org.openrewrite.kotlin.internal.KotlinParserVisitor.visitElement(KotlinParserVisitor.kt:4509)
	at org.openrewrite.kotlin.internal.KotlinParserVisitor.visitFile(KotlinParserVisitor.kt:166)
	at org.openrewrite.kotlin.KotlinParser.lambda$parseInputs$3(KotlinParser.java:176)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:272)
...
```

**Comment by traceyyoshima** [comment]
Fixed in PSI parser
