### ISSUE TITLE
Error parsing anonymous object

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite-kotlin#373]
The following test
```java
    @Test
    void error() {
        rewriteRun(
          kotlin(
            """
              open class Object<T>
              class Test(name: String, any: Any)
              
              fun <T> foo(name: String) =
                  Test(name, object : Object<T>() {
                  })
              """
          )
        );
    }
```
prints this error when run
```
Caused by: java.lang.ClassCastException: class org.openrewrite.java.tree.JavaType$Variable cannot be cast to class org.openrewrite.java.tree.JavaType$FullyQualified (org.openrewrite.java.tree.JavaType$Variable and org.openrewrite.java.tree.JavaType$FullyQualified are in unnamed module of loader 'app')
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitObjectDeclaration(KotlinTreeParserVisitor.java:2644)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitObjectDeclaration(KotlinTreeParserVisitor.java:69)
	at org.jetbrains.kotlin.psi.KtObjectDeclaration.accept(KtObjectDeclaration.kt:63)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitObjectLiteralExpression(KotlinTreeParserVisitor.java:2569)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitObjectLiteralExpression(KotlinTreeParserVisitor.java:69)
	at org.jetbrains.kotlin.psi.KtObjectLiteralExpression.accept(KtObjectLiteralExpression.java:30)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitArgument(KotlinTreeParserVisitor.java:1726)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitArgument(KotlinTreeParserVisitor.java:69)
	at org.jetbrains.kotlin.psi.KtValueArgument.accept(KtValueArgument.java:46)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.mapFunctionCallArguments(KotlinTreeParserVisitor.java:3766)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitCallExpression(KotlinTreeParserVisitor.java:1883)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitCallExpression(KotlinTreeParserVisitor.java:69)
	at org.jetbrains.kotlin.psi.KtCallExpression.accept(KtCallExpression.java:35)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.convertToBlock(KotlinTreeParserVisitor.java:3324)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitNamedFunction0(KotlinTreeParserVisitor.java:2530)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitNamedFunction(KotlinTreeParserVisitor.java:2414)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitNamedFunction(KotlinTreeParserVisitor.java:69)
	at org.jetbrains.kotlin.psi.KtNamedFunction.accept(KtNamedFunction.java:51)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitKtFile(KotlinTreeParserVisitor.java:1649)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.parse(KotlinTreeParserVisitor.java:104)
	at org.openrewrite.kotlin.KotlinParser.lambda$parseInputs$4(KotlinParser.java:185)
	... 18 more
```

**Comment by kunli2** [comment]
fixed by https://github.com/openrewrite/rewrite-kotlin/commit/314267ff30e344336a301a95d380959e4decef47
