### ISSUE TITLE
`J$ParameterizedType` cannot be cast to class `MethodCall`

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite-kotlin#376]
The following test
```java
    @Test
    void error() {
        rewriteRun(
          kotlin(
            """
              val x: MutableMap<String, String> = hashMapOf()
              val keys = x.entries.map(MutableMap.MutableEntry<String, String>::key)
              """
          )
        );
    }
```
results in the following error:
```
Caused by: java.lang.ClassCastException: class org.openrewrite.java.tree.J$ParameterizedType cannot be cast to class org.openrewrite.java.tree.MethodCall (org.openrewrite.java.tree.J$ParameterizedType and org.openrewrite.java.tree.MethodCall are in unnamed module of loader 'app')
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitDotQualifiedExpression(KotlinTreeParserVisitor.java:2283)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitDotQualifiedExpression(KotlinTreeParserVisitor.java:69)
	at org.jetbrains.kotlin.psi.KtDotQualifiedExpression.accept(KtDotQualifiedExpression.kt:32)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitCallableReferenceExpression(KotlinTreeParserVisitor.java:284)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitCallableReferenceExpression(KotlinTreeParserVisitor.java:69)
	at org.jetbrains.kotlin.psi.KtCallableReferenceExpression.accept(KtCallableReferenceExpression.java:51)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitArgument(KotlinTreeParserVisitor.java:1726)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitArgument(KotlinTreeParserVisitor.java:69)
	at org.jetbrains.kotlin.psi.KtValueArgument.accept(KtValueArgument.java:46)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.mapFunctionCallArguments(KotlinTreeParserVisitor.java:3766)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitCallExpression(KotlinTreeParserVisitor.java:1890)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitCallExpression(KotlinTreeParserVisitor.java:69)
	at org.jetbrains.kotlin.psi.KtCallExpression.accept(KtCallExpression.java:35)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitDotQualifiedExpression(KotlinTreeParserVisitor.java:2283)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitDotQualifiedExpression(KotlinTreeParserVisitor.java:69)
	at org.jetbrains.kotlin.psi.KtDotQualifiedExpression.accept(KtDotQualifiedExpression.kt:32)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitProperty(KotlinTreeParserVisitor.java:2749)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitProperty(KotlinTreeParserVisitor.java:69)
	at org.jetbrains.kotlin.psi.KtProperty.accept(KtProperty.java:58)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitKtFile(KotlinTreeParserVisitor.java:1649)
	at org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.parse(KotlinTreeParserVisitor.java:104)
	at org.openrewrite.kotlin.KotlinParser.lambda$parseInputs$4(KotlinParser.java:185)
	... 18 more
```

**Comment by kunli2** [comment]
fixed by https://github.com/openrewrite/rewrite-kotlin/commit/4fb2f02a64948fcbb2b1e91c1eeecfaabbdad953
